exclude: node_modules
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: detect-private-key
  - repo: local
    hooks:
      - id: toTemplateDeps.zsh
        name: toTemplateDeps.zsh
        entry: \./\.commitHooks/toTemplateDeps.zsh
        files: package.json
        language: script
        stages: [pre-commit]
        always_run: true
      - id: formatPackageJson.zsh
        name: formatPackageJson.zsh
        entry: \./\.commitHooks/formatPackageJson.zsh
        files: package.json
        language: script
        stages: [pre-commit]
        always_run: true
      - id: toWorkspaceDeps.zsh
        name: toWorkspaceDeps.zsh
        entry: \./\.commitHooks/toWorkspaceDeps.zsh
        files: package.json
        language: script
        stages: [post-commit]
        always_run: true
